require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/**
    - vendor/**/*
    - tmp/**/*
    - db/schema.rb
  TargetRubyVersion: 3.3

# Layout rules
Layout/LineLength:
  Max: 120

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

# Style rules
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'db/schema.rb'

Style/ClassAndModuleChildren:
  Enabled: true

Style/Documentation:
  Enabled: false # eventually enable

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/IndentationWidth:
  Width: 2

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

# Metrics rules
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/development.rb'
    - 'db/migrate/*.rb'
  Max: 25

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
  Max: 10

Metrics/ClassLength:
  Max: 100

# Lint rules
Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

# Naming rules
Naming/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

Naming/PredicateName:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: true

# Rails-specific rules
Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HttpStatus:
  EnforcedStyle: symbolic

Rails/SkipsModelValidations:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - performance
    - qa
    - staging

# RSpec rules
RSpec:
  Enabled: true

RSpec/Focus:
  Enabled: true

RSpec/ImplicitSubject:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/NestedGroups:
  Max: 3

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

