default: &default
  adapter: mysql2
  host: mysql
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch('DB_CONNECTIONS') { ENV.fetch('RAILS_MAX_THREADS', 5) } %>

test:
  <<: *default
  database: <%= Rails.application.credentials.database.name %>
  username: <%= Rails.application.credentials.database.user %>
  password: <%= Rails.application.credentials.database.password %>

development:
  <<: *default
  database: <%= Rails.application.credentials.database.name %>
  username: <%= Rails.application.credentials.database.user %>
  password: <%= Rails.application.credentials.database.password %>

production:
  <<: *default
  database: <%= Rails.application.credentials.database.name %>
  username: <%= Rails.application.credentials.database.user %>
  password: <%= Rails.application.credentials.database.password %>
